### ISSUE TITLE
[Pago V1.0.0] Bug report

### ISSUE THREAD

**Issue by Ariel1206** [Pago-TW/report-center#2]
- [x] 1. 聊天室訊息會跑到header之上、輸入框要往下拉才看的到，不夠直觀

https://user-images.githubusercontent.com/105278732/236673712-6cf4ab46-4c2f-4712-9729-5d1127fcf7a9.mp4

- [x] 2. 無法發布委託

https://user-images.githubusercontent.com/105278732/236674066-9254a791-c6fe-4fd7-aa16-756feb0e4ff7.mp4

**Comment by EnderWolf50** [comment]
1. 網頁基本上都會擠上去，要固定的話好像要算有的沒的高度，不是很經濟實惠 🤔
2. 後端資料庫購買地址欄位長度過短，已修復

先關起來如果你覺得真的非修不可再打開，但我也是之後才會想辦法 🥴
