### ISSUE TITLE
[Pago V1.0.0] Bug report

### ISSUE THREAD

**Issue by Ariel1206** [Pago-TW/report-center#3]
- [x] 神奇的stepper
![bug](https://github.com/Pago-TW/report-center/assets/105278732/690bc25b-8f62-4e56-b952-443e8e5f0537)

**Comment by EnderWolf50** [comment]
_reason: 在使用 - 按鈕的時候 `value` 被強制寫為負數，但呈現的時候不允許負數，導致呈現數值與實際數值不一_

已修復
