### ISSUE TITLE
report Bug

### ISSUE THREAD

**Issue by Nightmare0709** [Pago-TW/report-center#6]
1.即將出發的旅途可完成所有交易流程。
![image](https://github.com/Pago-TW/report-center/assets/104414757/9cdbf39d-6692-4143-b5e9-0695bbd33464)
![image](https://github.com/Pago-TW/report-center/assets/104414757/aeafed19-b089-4950-b935-673db09fdf65)

2.Footer的 [設定] 未成功導向正確頁面
![image](https://github.com/Pago-TW/report-center/assets/104414757/3dbb4c3a-f640-4c57-8dd8-376df35e8008)
![image](https://github.com/Pago-TW/report-center/assets/104414757/efa2390b-cb5d-4c63-aa05-e6cda6506ddf)

3.已完成的評價星等沒有反映在會員資料上
![image](https://github.com/Pago-TW/report-center/assets/104414757/7c0e5b40-fa46-4a8f-9736-206f6668db45)

**Comment by sh1un** [comment]
> 1.即將出發的旅途可完成所有交易流程。

雖無造成功能影響，但應製作防呆，這將在後續開會討論解方

> 2.Footer的 [設定] 未成功導向正確頁面 ![image](https://user-images.githubusercontent.com/104414757/271997375-3dbb4c3a-f640-4c57-8dd8-376df35e8008.png) ![image](https://user-images.githubusercontent.com/104414757/271997417-efa2390b-cb5d-4c63-aa05-e6cda6506ddf.png)

已將此 Bug 在前端 Repo 發出 Ticket
https://github.com/Pago-TW/pago-frontend/issues/56

> 3.已完成的評價星等沒有反映在會員資料上 ![image](https://user-images.githubusercontent.com/104414757/271998153-7c0e5b40-fa46-4a8f-9736-206f6668db45.png)
經重複檢測後，目前此功能是正常的，故先排除此 Bug
