### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Ariel1206** [Pago-TW/report-center#7]
- [ ] 1. 標籤未顯示 
- ![image](https://github.com/Pago-TW/report-center/assets/105278732/8eb9a8e1-c501-4a44-a05f-0f24c21fb861)

- [ ] 2. 重新登入問題
- 已經登入過後，點擊sidebar進入別的分頁，卻要求重新登入
- (好像不是只有錢包頁面會這樣，我上一次測試是我的委託頁面要重新登入)
- ![login bug](https://github.com/Pago-TW/report-center/assets/105278732/faf645b9-d257-43ca-ba67-df081cfffc19)

- [ ] 3. 旅途管理頁面(trips)最新和最舊邏輯相反
- 最舊的應該把日期越久遠的放在上面
- ![trips bug](https://github.com/Pago-TW/report-center/assets/105278732/f766c9af-a6ae-4821-a23a-d5f02c2ce4ba)

- [ ] 4. 關於我們頁面(about-us)陳俊廷職位錯誤
- ![image](https://github.com/Pago-TW/report-center/assets/105278732/bacfd1b3-9827-4e9d-813d-14130f0296b6)

**Comment by sh1un** [comment]
已將上述 Bug 整理完畢發出 ticket
https://github.com/Pago-TW/pago-frontend/issues/56
https://github.com/Pago-TW/pago-frontend/issues/57
